name: Base Styles
description: Base styles for the Callisto theme
type: core

form:
  fields:

    background:
      type: input.colorpicker
      label: Base Background
      default: "#1f1f1f"
    text-color:
      type: input.colorpicker
      label: Base Text Color
      default: "#888888"
    favicon:
       type: input.imagepicker 
       label: Favicon 
       filter: '.(jpe?g|gif|png|svg|ico)$'
